
</main>

<footer class="site-footer py-3 mt-4 bg-light">
    <div class="container text-center">
        <p class="mb-0">&copy; <?= date('Y') ?> TickSight UK – by Jennifer Kamara</p>
    </div>
</footer>

<!-- Bootstrap js bundle -->
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"
></script>

<script src="../../js/main.js"></script>
<script src="../../js/accessibility.js"></script>


</body>
</html>

